cmake_minimum_required(VERSION 3.20)
project(cppToCUDAExpressionTemplateTraining CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_subdirectory(lessons/00_pointer_reference_sugar)
add_subdirectory(lessons/01_raii)
add_subdirectory(lessons/02_rule_of_3)
add_subdirectory(lessons/03_rule_of_5)
add_subdirectory(lessons/04_rule_of_0)
add_subdirectory(lessons/05_rule_of_0_composed/)
add_subdirectory(lessons/06_templates)
add_subdirectory(lessons/07_crtp)
add_subdirectory(lessons/08_forwarding_references)
add_subdirectory(lessons/09_smart_pointers)